default: &default
  adapter: postgresql
  encoding: utf-8
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_MASTER_HOST'] %>
  port: <%= ENV['POSTGRES_MASTER_PORT'] %>
  database: <%= ENV["POSTGRES_DB"] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default