version: '3.2'

services:
  web:
    container_name: ${APP_NAME}
    build:
      context: ${PWD}/
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    command: bundle exec puma -C config/puma.rb
    networks:
      - rails-network
    volumes:
      - ${PWD}:/workspace/${APP_NAME}
      - gems:/gems
    env_file:
      - '.env'
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - db
    restart: always
  db:
    container_name: db
    image: postgres:9.6.20
    volumes:
     - postgres-db:/data/db
    networks:
      - rails-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure:5

volumes:
  gems:
  postgres-db:

networks:
  rails-network: